version: "3"

services:
  mawaqit-api:
    image: mrsofiane/mawaqit-api:latest
    ports:
      - "80:80"
    depends_on:
      - mawaqit-api-redis
    env_file:
      - .env

  mawaqit-api-redis:
    image: redis:alpine3.18
    ports:
      - "6379:6379"
